# fly.toml app configuration file generated for ncuber-backend on 2023-05-31T00:08:29+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ncuber-backend"
primary_region = "nrt"

[build]
  builder = "paketobuildpacks/builder:full"

[env]
  PORT = "5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
